// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkQnQ5jEVvDZ67Sysk6rlR5bn0S9MIXc8',
    appId: '1:403937251543:web:bbf9277ca07fa63e9f2092',
    messagingSenderId: '403937251543',
    projectId: 'imcd-95390',
    authDomain: 'imcd-95390.firebaseapp.com',
    storageBucket: 'imcd-95390.appspot.com',
    measurementId: 'G-SEQDW6GKCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGNJXRclGO4NbVNuURcDSyqdd3n0MJdvU',
    appId: '1:403937251543:android:f4b91dbdee5de3349f2092',
    messagingSenderId: '403937251543',
    projectId: 'imcd-95390',
    storageBucket: 'imcd-95390.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUknaxBPEwaNEFJJgeVb8IE1FCqq3J-fM',
    appId: '1:403937251543:ios:d78cfc139d24cdae9f2092',
    messagingSenderId: '403937251543',
    projectId: 'imcd-95390',
    storageBucket: 'imcd-95390.appspot.com',
    iosBundleId: 'com.example.imcd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUknaxBPEwaNEFJJgeVb8IE1FCqq3J-fM',
    appId: '1:403937251543:ios:d78cfc139d24cdae9f2092',
    messagingSenderId: '403937251543',
    projectId: 'imcd-95390',
    storageBucket: 'imcd-95390.appspot.com',
    iosBundleId: 'com.example.imcd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkQnQ5jEVvDZ67Sysk6rlR5bn0S9MIXc8',
    appId: '1:403937251543:web:e097b71bcab08ddc9f2092',
    messagingSenderId: '403937251543',
    projectId: 'imcd-95390',
    authDomain: 'imcd-95390.firebaseapp.com',
    storageBucket: 'imcd-95390.appspot.com',
    measurementId: 'G-LPXW9WEYXK',
  );
}
